metagenome_dir: data/metagenomes/

sample_info: samples.csv

display_genomes: True # for mkdocs, temporarily...
genomes:
- data/genomes/*.fa.gz

run_gather: True

databases:
- ../sourmash/podar-ref.zip

taxonomies:
- ../sourmash/podar-ref/podar-lineage.csv
