site_name: sourmash slainte

theme:
   name: material

plugins:
- search
- macros:
     module_name: slainte_functions
     include_yaml:
       - config.yml
markdown_extensions:
- admonition
- pymdownx.details
- pymdownx.superfences
- pymdownx.tasklist:
    custom_checkbox: true
    clickable_checkbox: true
