site_name: sourmash slainte

theme:
   name: material

plugins:
- search
- table-reader

markdown_extensions:
- admonition
- pymdownx.details
- pymdownx.superfences
- pymdownx.tasklist:
    custom_checkbox: true
    clickable_checkbox: true
